### ISSUE TITLE
[QUESTION] Why does building this repo first fetch the existing/current database?

### ISSUE THREAD

**Issue by david-bakin** [vector-of-bool/dds-ports#3]
As part of building this repo the existing/current database is fetched from the deployed location (target `wget-repo-db` in the `Makefile`), (if that fails then it does an `init-repo` target which runs `bpt init --if-exists=ignore` on it, creating it).

The question is: why doesn't it simply start from scratch each time without fetching the previous version?  Doesn't it collect all the information again anyway for all the ports it knows about?  What is it keeping from the previous database?

**Comment by vector-of-bool** [comment]
Because of the way the repository data is built and uploaded to the public server, the build only needs to actually generate package files for packages that aren't already present in the public repository. It also needs to add those entries to the SQLite database. By fetching the existing SQLite database, the repository "pretends" that it is already fully populated with the existing packages without needing to actually download the binaries. This allows every repository build to skip over every package that has already been processed.
